### PR TITLE
Implementation of full-duplex mode

### PR DESCRIPTION
**Pull request by tjaskula**
Ongoing implementation of full-duplex mode

### CODE REVIEW

**Comment by tjaskula** [comment]
Test of the notification

**Comment by tjaskula** [comment]
I'm done with this PR. It's ready to review @zpbappi @VaughnVernon. I'll merge it soon to start working on the rest

**Comment by VaughnVernon** [comment]
@tjaskula @zpbappi I will not have time to review this until next week. Please carry on without me. My only concern is that we are using actors rather than separate threading/tasks to manage the socket readers and writers. I understand that there might be no other way, but I want to make sure that that is the case.

**Comment by tjaskula** [comment]
@VaughnVernon This is how it works on the Java side. I tried to stick as much as possible to the reference implementation. Btw, `IntervalSignal` method of the actor is called by the scheduler on potentially different thread, and .NET Sockets are thread safe. Also using Async IOCP of the socket I'm not blocking threads while reading and writing.

**Comment by VaughnVernon** [comment]
@tjaskula In terms of the actor model the correct thing to do would be to send the actor a message containing the received data. It seems in your case that would alleviate the need to timer signals, wouldn't it? Sorry I am only guess since I have not yet had time to review the code, but if the socket reader is itself interrupt driven by available data, it would need the scheduling is unnecessary. Sending the actor a message assures multiple threads don't access its state simultaneously.

**Comment by tjaskula** [comment]
You'd like to have a periodic check if socket has available data, so either way, sending just a message is not enough.

**Comment by tjaskula** [comment]
@VaughnVernon @zpbappi Any comments/remarks I'll address in separate PR

**Pull request merged**
